package com.example.aula18_12_24;

import android.content.Intent;
import android.os.Bundle;
import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);

        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        List<Movie> movieList = new ArrayList<>();
        movieList.add(new Movie("Solo Leveling: ReAwakening", R.drawable.movie01, "05/12/2024", 8.1, "Over a decade after 'gates' connecting worlds appeared, awakening 'hunters' with superpowers, weakest hunter Sung Jinwoo encounters a double dungeon and accepts a mysterious quest, becoming the only one able to level up, changing his fate", R.drawable.categoria_18anos));
        movieList.add(new Movie("Moana 2", R.drawable.movie02, "28/11/2024", 3.7, "Sequência da já clássica animação musical da Disney, Moana 2 acompanha o reencontro de Moana e Maui para uma nova aventura pelos mares. Passados três anos desde a última jornada marítima, um chamado de seus ancestrais leva a jovem polinésia Moana de volta para águas perigosas e distantes da Oceania com um grupo improvável de marinheiros. Com a ajuda também do semideus Maui, ela deve quebrar uma maldição terrível que um deus cruel e com sede de poder colocou sobre uma das ilhas de seu povo. Nessa grandiosa missão, Moana e sua equipe vão desbravar novos territórios e enfrentar velhos e novos inimigos, como monstros marítimos, feitiços e deuses do mal. Tudo isso em busca de reconectar sua nação e assegurar a paz dos oceanos.", R.drawable.categoria_livre));
        movieList.add(new Movie("Hellboy e o Homem Torto", R.drawable.movie03, "24/10/2024", 2.4, "Hellboy se une a um agente novato da B.P.D.P. na década de 1950 e são enviados para os Apalaches. Lá, descobrem uma remota e assombrada comunidade, dominada por bruxas e liderada pelo sinistro demônio local, conhecido como O Homem Torto. À medida que exploram os mistérios sombrios deste lugar isolado, Hellboy confronta segredos enterrados de seu próprio passado, levando-o a uma batalha épica contra forças malignas que ameaçam desencadear o caos sobre o mundo.", R.drawable.categoria_16anos));
        movieList.add(new Movie("Howl's Moving Castle", R.drawable.movie04, "15/07/2005", 8.2, "Uma bruxa lança uma terrível maldição sobre a jovem Sophie transformando-a em uma velha. Desesperada, ela embarca em uma odisseia em busca do mago Howl, um misterioso feiticeiro que pode ajudá-la a reverter o feitiço.", R.drawable.categoria_livre));
        movieList.add(new Movie("Transformers One", R.drawable.movie05, "02/12/2024", 7.5, "Transformers: O Início mostrará os autobots para uma nova aventura épica. O filme contará a origem da rivalidade entre Optimus Prime, dublado por Chris Hemsworth na versão original, e Megatron, que terá a voz de Brian Tyree Henry. Além da dupla de protagonistas, o querido Bumblebee será dublado por Keegan-Michael Key. A produção de John Cooley se passa no planeta de Cybertron e não terá interação com os seres humanos no Planeta Terra, como nos outros filmes da franquia. A trama mostra como Optimus Prime e Megatron já foram melhores amigos, quase irmãos, com uma grande ligação e viraram inimigos jurados. O longa mostrará a origem do que viria a se tornar, mais tarde, o conflito entre Autobots e Decepticons, que mudou a história de Cybertron e até do Planeta Terra.", R.drawable.categoria_10anos));
        movieList.add(new Movie("The Super Mario Bros. Movie", R.drawable.movie06, "07/04/2023", 7.3, "Após se encontrar no Reino dos Cogumelos e seu irmão ser raptado pelo Rei dos Koopas, Mario embarca em uma viagem para salvar todo o reino e Luigi. Ele ainda estará companhado de Toad, Princesa Peach e Donkey Kong.", R.drawable.categoria_livre));
        movieList.add(new Movie("Barbie", R.drawable.movie07, "20/07/2023", 7.1, "No fabuloso live-action da boneca mais famosa do mundo, acompanhamos o dia a dia em Barbieland - o mundo mágico das Barbies, onde todas as versões da boneca vivem em completa harmonia e suas únicas preocupações são encontrar as melhores roupas para passear com as amigas e curtir intermináveis festas. Porém, uma das bonecas (interpretada por Margot Robbie) começa a perceber que talvez sua vida não seja tão perfeita assim, questionando-se sobre o sentido de sua existência e alarmando suas companheiras. Logo, sua vida no mundo cor-de-rosa começa a mudar e, eventualmente, ela sai de Barbieland. Forçada a viver no mundo real, Barbie precisa lutar com as dificuldades de não ser mais apenas uma boneca - pelo menos ela está acompanhada de seu fiel e amado Ken (Ryan Gosling), que parece cada vez mais fascinado pela vida no novo mundo. Enquanto isso, Barbie tem dificuldades para se ajustar, e precisa enfrentar vários momentos nada coloridos até descobrir que a verdadeira beleza está no interior de cada um.", R.drawable.categoria_livre));
        movieList.add(new Movie("Shrek 5", R.drawable.movie08, "25/11/2026", 7.8, "Quinto filme da franquia Shrek. A sinopse ainda não foi divulgada.\n Confira a classificação indicativa no Portal Online da Cultura Digital.", R.drawable.categoria_livre));
        movieList.add(new Movie("Red One", R.drawable.movie09, "07/12/2024", 6.9, "Operação Natal é um longa do diretor Jake Kasdan com os astros Dwayne Johnson, o famoso The Rock, Chris Evans, famoso por sua interpretação como Capitão América nos filmes da franquia Marvel, e Lucy Liu, que tem destaques como Kill Bill e As Panteras em sua filmografia. Depois de um sequestro chocante que abalou o Polo Norte, o Comandante da Força Tarefa (ELF), Callum Drift (Dwayne Johnson), deverá fazer uma parceria com o mais famoso caçador de recompensas do mundo, Jack O'Malley (Chris Evans), para salvar o Natal de diversas crianças e adultos ao redor do mundo. Isso porque a vítima do sequestro foi ninguém mais e ninguém menos que o Papai Noel e essa dupla dinâmica não o recuperar a tempo, o Natal estará perdido. Essa comédia de ação e aventura contagiante tem quatro quadrantes e é aberto um universo totalmente novo para explorar dentro desse gênero de férias natalinas.", R.drawable.categoria_livre));
        movieList.add(new Movie("Snow White", R.drawable.movie10, "22/04/2025", 8.0, "No mais novo live-action Branca de Neve, quando a Rainha Má (Gal Gadot)  manda matarem sua enteada por inveja de sua beleza, Branca de Neve (Rachel Zegler) foge do reino. Ela percorre a floresta e acha uma casinha onde vivem sete anões amigáveis com quem passa viver. Porém, a moça ainda não está a salvo, já que a bruxa planeja dar um fim a sua vida com uma maçã envenenada. O live-action da Disney vai reimaginar a história do clássico, além de novas canções originais de Benj Pasek e Justin Paul, compositores responsáveis por La La Land e O Rei do Show.", R.drawable.categoria_livre));
        movieList.add(new Movie("Paddington in Peru", R.drawable.movie11, "25/11/2024", 7.5, "Em Paddington - Uma Aventura na Floresta, o adorável urso Paddington retorna ao Peru para visitar sua querida Tia Lucy, acompanhado pela família Brown. A viagem, que promete ser uma reunião afetuosa, logo se transforma em uma jornada cheia de surpresas e mistérios a serem resolvidos. Enquanto explora a floresta amazônica, Paddington e seus amigos encontram uma variedade de desafios inesperados e se deparam com a deslumbrante biodiversidade do local. Além de garantir muita diversão para o público, o filme aborda temas de amizade e coragem, proporcionando uma experiência emocionante para toda a família. Bruno Gagliasso, mais uma vez, empresta sua voz ao personagem na versão brasileira, adicionando um toque especial ao carismático urso. Com estreia marcada para 16 de janeiro, o longa promete encantar as crianças nas férias e já conquistou o público com um trailer inédito que antecipa as aventuras que aguardam Paddington e a família Brown no coração da Amazônia.", R.drawable.categoria_livre));
        movieList.add(new Movie("Lilo & Stitch", R.drawable.movie12, "13/06/2025", 7.6, "Live-action do famoso clássico de animação da Disney, Lilo & Stitch, onde Stitch (Chris Sanders), o experimento 626, é um alienígena expressivo que foi adotado como animal de estimação por Lilo (Maia Kealoha) e juntos eles descobrem o significado de família.", R.drawable.categoria_livre));
        movieList.add(new Movie("Venom: The Last Dance", R.drawable.movie13, "17/07/2025", 7.3, "O filme contará com cenas eletrizantes, com Venom devorando inimigos enquanto luta ao lado de Eddie. A situação se complica quando outros alienígenas do planeta de Venom descobrem seu paradeiro e chegam à Terra com a missão de capturá-lo. A aliança inseparável entre Eddie e Venom é posta à prova como nunca antes, enfrentando ameaças implacáveis e perigos de todos os lados.", R.drawable.categoria_16anos));
        movieList.add(new Movie("A Minecraft Movie", R.drawable.movie14, "03/12/2025", 6.8, "Um Filme Minecraft é a primeira adaptação live-action para os cinemas do jogo mais vendido de todos os tempos, Minecraft. Neste universo onde a criatividade não só proporciona diversão como também é vital para a sobrevivência, quatro indivíduos desajustados — Garrett arrett “The Garbage Man” Garrison (Jason Momoa), Henry (Sebastian Eugene Hansen), Natalie (Emma Myers) e Dawn (Danielle Brooks) — são subitamente transportados para o Overworld, um mundo cúbico e bizarro onde a imaginação reina. Após passarem por um portal misterioso, eles se encontram em uma terra repleta de perigos e criaturas malignas, como Piglins e Zumbis. Para retornarem ao seu mundo, eles terão que dominar este novo ambiente com a ajuda de um construtor experiente e imprevisível, Steve (Jack Black). Durante essa jornada mágica, os cinco aventureiros precisarão redescobrir suas habilidades únicas, essenciais não apenas para sobreviver no Overworld, mas também para prosperar na vida real.", R.drawable.categoria_livre));
        movieList.add(new Movie("Mufasa: The Lion King", R.drawable.movie15, "15/07/2025", 7.9, "Prólogo do live action de Rei Leão, produzido pela Disney e dirigido por Barry Jenkins, o longa contará a história de Mufasa e Scar antes de Simba. A trama tem a ajuda de Rafiki, Timão e Pumba, que juntos contam a lenda de Mufasa à jovem filhote de leão Kiara, filha de Simba e Nala. Narrado através de flashbacks, a história apresenta Mufasa como um filhote órfão, perdido e sozinho até que ele conhece um simpático leão chamado Taka – o herdeiro de uma linhagem real. O encontro ao acaso dá início a uma grande jornada de um grupo extraordinário de deslocados em busca de seu destino, além de revelar a ascensão de um dos maiores reis das Terras do Orgulho.", R.drawable.categoria_livre));
        movieList.add(new Movie("Captain America: Brave New World", R.drawable.movie16, "02/05/2025", 8.2, "Capitão América: Admirável Mundo Novo é o próximo filme do famoso herói da Marvel. Desta vez, o filme dá continuidade à minissérie de televisão Falcão e o Soldado Invernal, onde o escudo está nas mãos de Sam Wilson (Anthony Mackie), após Steve Rogers (Chris Evans) o entregar em Vingadores: Ultimato.", R.drawable.categoria_12anos));
        movieList.add(new Movie("Godzilla: Minus One", R.drawable.movie17, "11/12/2025", 7.4, "O temido Godzilla retorna e ataca uma cidade japonesa devastada após a Segunda Guerra Mundial.", R.drawable.categoria_12anos));
        movieList.add(new Movie("Karate Kid: Legends", R.drawable.movie18, "24/09/2025", 6.7, "Em Karate Kid: Lendas, teremos a volta de de Daniel LaRusso (Ralph Macchio) e de Mr. Han (Jackie Chan) nesse filme que abarca todos os universos da franquia, desde a trilogia original dos anos 80 até o remake de 2010 com Jackie Chan e Jaden Smith e a série Cobra Kai. O filme acompanha a ida de Daniel para a China onde Mr. Han o procura com seu novo pupilo, Li Fong. Apesar de abordagens diferentes, os dois mentores se juntam para instruir o mais novo aprendiz.", R.drawable.categoria_10anos));
        movieList.add(new Movie("Gladiator II", R.drawable.movie19, "13/11/2025", 8.0, "Na sequência do filme dirigido por Ridley Scott nos anos 2000, 25 anos após testemunhar a morte do herói Maximus pelas mãos de seu tio, Lucius enfrenta um novo desafio após ter sua casa tomada pelos imperadores tirânicos que governam Roma com punho de ferro. Agora ele precisa reencontrar a força e a coragem que o inspiraram na juventude e sobreviver aos jogos no Coliseu.", R.drawable.categoria_16anos));
        movieList.add(new Movie("Joker: Folie à Deux", R.drawable.movie20, "14/10/2025", 8.4, "Em Coringa 2, acompanhamos a sequência do longa sobre Arthur Fleck (Joaquin Phoenix), que trabalhava como palhaço para uma agência de talentos e precisou lidar desde sempre com seus problemas mentais. Vindo de uma origem familiar complicada, sua personalidade nada convencional o fez ser demitido do emprego, e, numa reação a essa e tantas outras infelicidades em sua vida, ele assumiu uma postura violenta - e se tornou o Coringa. A continuação se passa depois dos acontecimentos do filme de 2019, após ser iniciado um movimento popular contra a elite de Gotham City, revolução esta, que teve o Coringa como seu maior representante. Preso no hospital psiquiátrico de Arkham, ele acaba conhecendo Harleen \"Lee\" Quinzel (Lady Gaga). A curiosidade mútua acaba se transformando em paixão e obsessão e eles desenvolvem um relacionamento romântico e doentio. Lee e Arthur embarcam em uma desventura alucinada, fervorosa e musical pelo submundo de Gotham City, enquanto o julgamento público d'O Coringa se desenrola, impactando toda a cidade e suas próprias mentes conturbadas.", R.drawable.categoria_18anos));

        MovieAdapter movieAdapter = new MovieAdapter(this, movieList);
        recyclerView.setAdapter(movieAdapter);

        movieAdapter.setOnItemClickListener(new MovieAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(Movie movie) {
                Intent intent = new Intent(MainActivity.this, MovieDatailActivity.class);
                intent.putExtra("movieTitle", movie.getTitle());
                intent.putExtra("moviePosterImage", movie.getPosterImage());
                intent.putExtra("descricao", movie.getOverview());
                intent.putExtra("pontuacao", movie.getRating());
                intent.putExtra("categoriaImage", movie.getCategoria());

                startActivity(intent);
            }
        });
    }
}